name: Deploy Docker to EC2

on:
  push:
    branches:
      - main  # This will trigger on any push to the main branch

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

  deploy_to_ec2:
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
    - name: Start SSH agent and add EC2 private key
      run: |
        echo "${{ secrets.EC2_PEM_KEY }}" > ec2-key.pem
        chmod 600 ec2-key.pem
        eval "$(ssh-agent -s)"
        ssh-add ec2-key.pem

    - name: SSH into EC2 and restart Docker
      run: |
        npm run build'
        echo "Frontend build completed. Starting backend deployment..."
        printf "%b" "$EC2_PEM_KEY" > ec2-key.pem
        chmod 600 ec2-key.pem
        scp  -o StrictHostKeyChecking=no -i ec2-key.pem -r ../backend/* ec2-user@$EC2_PUBLIC_IP:/home/ec2-user/backend/

        ssh -o StrictHostKeyChecking=no -i ec2-key.pem ec2-user@ec2-3-94-252-58.compute-1.amazonaws.com << 'EOF'
          
          cd /home/ec2-user/backend/
          pm2 restart index.js || pm2 start index.js

        EOF
